version: '2'
services:
  web:
    image: adampoit/redditmarkov-web
    links:
      - ardb
    ports:
      - "8080"
  loader:
    image: adampoit/redditmarkov-loader
    links:
      - ardb
  ardb:
    image: adampoit/ardb-server
    ports:
      - "6379:36380"
    volumes:
      - data:/var/lib/ardb
volumes:
  data: {}
